Initial working simulator
clearpathrobotics/clearpath_simulator pull request #1
Opened 2023-05-24 20:33 UTC by roni-kreinin

Depends on https://github.com/clearpathrobotics/clearpath_common/pull/12

Basic teleop works with A200.

2023-05-26 19:52 UTC, tonybaltovski requested changes

2023-05-26 19:52 UTC, tonybaltovski commented on launch/clearpath_simulator.launch.py
> +    DeclareLaunchArgument('model', default_value='standard',
I think these need to be updated.

2023-05-26 19:52 UTC, tonybaltovski commented on launch/gz_sim.launch.py
> +    DeclareLaunchArgument('model', default_value='lite',
Update for Clearpath Platforms.

2023-05-26 19:52 UTC, tonybaltovski commented on launch/robot_spawn.launch.py
> +    DeclareLaunchArgument('model', default_value='standard',
Update for Clearpath Platforms.

2023-05-26 19:52 UTC, tonybaltovski commented on launch/robot_spawn.launch.py
> +    DeclareLaunchArgument('localization', default_value='false',
Should localization, slam and nav2 be moved out to its own launch files?

2023-05-30 18:05 UTC, tonybaltovski commented on launch/gz_sim.launch.py
> +    DeclareLaunchArgument('model', default_value='lite',
@roni-kreinin this change?

2023-05-30 18:38 UTC, roni-kreinin commented on launch/gz_sim.launch.py
> +    DeclareLaunchArgument('model', default_value='lite',
Fixed.

2023-05-30 18:43 UTC, tonybaltovski approved these changes

2023-05-30 18:53 UTC, merged