Add A300 to supported platforms
clearpathrobotics/clearpath_simulator pull request #63
Opened 2024-12-06 16:31 UTC by civerachb-cpr

2024-12-09 21:14 UTC, roni-kreinin requested changes

2024-12-09 21:14 UTC, roni-kreinin commented on clearpath_generator_gz/clearpath_generator_gz/launch/generator.py
> +            Platform.A300: [
Lets make a common platform components array to hold the cmd_vel_node and odom_base_node since all robots will use these. Same way we did it here: https://github.com/clearpathrobotics/clearpath_robot/blob/a88192de11edf7425e968fd9fa730435181fff3c/clearpath_generator_robot/clearpath_generator_robot/launch/generator.py#L231

2024-12-09 21:43 UTC, civerachb-cpr commented on clearpath_generator_gz/clearpath_generator_gz/launch/generator.py
> +            Platform.A300: [
Taken a first-pass at implementing this.

2024-12-16 16:15 UTC, roni-kreinin commented on clearpath_generator_gz/clearpath_generator_gz/launch/generator.py
> +        for component in self.latform_components[self.platform_model]:
Typo

2024-12-16 16:43 UTC, civerachb-cpr commented on clearpath_generator_gz/clearpath_generator_gz/launch/generator.py
> +        for component in self.latform_components[self.platform_model]:
...how did that not trigger an error when i tested it? now i have so many questions about what's wrong with my environment. that's alarming...

2024-12-16 16:51 UTC, mhosmar-cpr commented
This may be a wider CI question but CI is failing to install clearpath_generator_common and clearpath_viz. Are these externally available?

2024-12-16 16:51 UTC, mhosmar-cpr approved these changes

2024-12-16 16:57 UTC, mhosmar-cpr commented
I'll answer my own question. They don't seem to be released in Jazzy yet.

2024-12-16 18:10 UTC, merged